server:
  port: 8083

spring:
  application:
    name: usage-billing-poc
  datasource:
    url: jdbc:h2:mem:usage;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2
